SELECT current_database();

DROP TABLE IF EXISTS Users;


CREATE TABLE Users (
    USER_ID VARCHAR(50) PRIMARY KEY,

    USER_ROLE VARCHAR(20) NOT NULL
        CHECK (USER_ROLE IN ('USER', 'CREATOR', 'ADMIN')),

    PASSWORD VARCHAR(100) NOT NULL,

    NICKNAME VARCHAR(30) NOT NULL UNIQUE,

    USERNAME VARCHAR(50) NOT NULL,

    BIRTHDATE DATE NOT NULL,

    PHONE_NUM VARCHAR(20) NOT NULL UNIQUE,

    EMAIL VARCHAR(100) NOT NULL UNIQUE,

    BANK_NAME VARCHAR(30),

    ACCOUNT_NUM VARCHAR(25),

    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE
);