SELECT current_database();

DROP TABLE IF EXISTS Users;

/* 유저 테이블 */
CREATE TABLE Users (
    USER_ID VARCHAR(50) PRIMARY KEY,

    USER_ROLE VARCHAR(20) NOT NULL
        CHECK (USER_ROLE IN ('USER', 'CREATOR', 'ADMIN')),

    PASSWORD VARCHAR(100) NOT NULL,

    NICKNAME VARCHAR(30) NOT NULL UNIQUE,

    USERNAME VARCHAR(50) NOT NULL,

    BIRTHDATE DATE NOT NULL,

    PHONE_NUM VARCHAR(20) NOT NULL UNIQUE,

    EMAIL VARCHAR(100) NOT NULL UNIQUE,

    BANK_NAME VARCHAR(30),

    ACCOUNT_NUM VARCHAR(25),

    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE
);


/* 프로젝트 테이블 */
CREATE TABLE Projects (
    PROJECT_ID BIGSERIAL PRIMARY KEY,

    CREATOR_ID VARCHAR(50) NOT NULL,

    TITLE VARCHAR(255) NOT NULL,

    THUMBNAIL_IMAGE VARCHAR(512),

    TARGET_AMOUNT NUMERIC(15, 2) NOT NULL
        CHECK (TARGET_AMOUNT > 0),

    START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,

    END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,

    STATUS VARCHAR(20) NOT NULL DEFAULT 'PREPARING'
        CHECK (STATUS IN ('PREPARING', 'ONGOING', 'SUCCESS', 'FAILED')),

    CONSTRAINT FK_Projects_Users
        FOREIGN KEY (CREATOR_ID)
        REFERENCES Users(USER_ID) ON DELETE RESTRICT,

    CONSTRAINT CK_Projects_Date
        CHECK (END_DATE > START_DATE)
);


/* 프로젝트 상세 내용 테이블*/
CREATE TABLE ProjectContent (
    PROJECT_ID BIGINT PRIMARY KEY,

    CONTENT_HTML TEXT NOT NULL,

    CONSTRAINT FK_ProjectContent_Projects
        FOREIGN KEY (PROJECT_ID)
        REFERENCES Projects(PROJECT_ID) ON DELETE CASCADE
);